site_name: Code Thesaurus Documentation

theme:
  name: material
  palette:
    scheme: default
    primary: blue
  font: false
  language: en
  icon:
    logo: material/library
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codethesaurus
repo_url: https://github.com/codethesaurus/docs/
repo_name: codethesaurus/docs
edit_uri: edit/main/docs/
plugins:
  - git-revision-date

nav:
- Home: index.md
- About/History: about.md
- Overview: overview.md
- Contributing: contributing.md
- Installation/Running Locally: install.md
- Website: website/index.md
- Thesaurus Files: thesaurus/index.md
- Project Architecture: project_architecture.md
- FAQs: faq/index.md
- Code of Conduct: CODE_OF_CONDUCT.md
- Code of Conduct Reporting: CODE_OF_CONDUCT_REPORTING.md
- Best Practices: Best_Practices.md
